# .github/workflows/ci.yml

name: CI Pipeline for Node.js and React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    # PostgreSQL サービスコンテナを起動 (バックエンドテスト用)
    services:
      postgres:
        image: postgres:14 
        env:
          POSTGRES_USER: nodeman      # テスト用ユーザー名 (任意)
          POSTGRES_PASSWORD: password # テスト用パスワード (任意)
          POSTGRES_DB: nodeplay  # テスト用データベース名 (任意)
        ports:
          - 5432:5432 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: ['23.11.0'] # テストするNode.jsバージョン (必要に応じて変更・追加)

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2. Node.jsのセットアップ
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm' 

      # --- Backend Steps (nodeplay) ---
      - name: Install backend dependencies
        uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: nodeplay/package-lock.json # バックエンドのロックファイルパス
      
      - name: Install backend dependencies
        run: npm ci
        working-directory: ./nodeplay

      - name: Run backend tests
        env:
          PGHOST: localhost # PostgreSQLサービスのホスト名
          PGPORT: 5432
          PGUSER: nodeman
          PGDATABASE: nodeplay
          PGPASSWORD: password
          NODE_ENV: test
        working-directory: ./nodeplay
        run: npm test --if-present # testスクリプト

      # --- Frontend Steps (reactplay/reactplay) ---
      - name: Install frontend dependencies
        uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: reactplay/reactplay/package-lock.json # フロントエンドのロックファイルパス

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./reactplay/reactplay

      - name: Run frontend tests
        env:
          CI: true 
        working-directory: ./reactplay/reactplay
        run: npm test --if-present

      - name: Build frontend
        env:
          REACT_APP_API_BASE_URL: http://54.197.120.188:3001/ 
        working-directory: ./reactplay/reactplay
        run: |
          echo "Verifying ENV VAR during build: REACT_APP_API_BASE_URL is $REACT_APP_API_BASE_URL"
          npm run build --if-present